### ISSUE TITLE
[Bug] Corporate card binding bug

### ISSUE THREAD

**Issue by slava110** [pkmnfrk/megacorp#106]
Second click needed to bind it
![bindbug](https://user-images.githubusercontent.com/26705162/48588788-91097280-e949-11e8-9337-7d1420efa651.gif)

**Comment by pkmnfrk** [comment]
I noticed this a long time ago (a month before the first public release), and spent a good 10 hours trying to fix it. I eventually gave up because I couldn't find a way to fix it. If you close and re-open the GUI you will see that it did, in fact, update.

The problem is that the linking process is instantaneous, and finishes before the server finishes sending the client the update for the UI. Basically it goes like this:

* You insert the card
* The GUI goes "oh, a change" and starts updating the client
* The server update the card, moving slots
* The client finishes updating
* The GUI goes "did anything change since I updated the client? No? Cool"

I'm not going to say that I will never fix it, but 1. I don't know how, and 2. It's a very minor bug.

**Comment by pkmnfrk** [comment]
So, I think the mere fact that this was reported caused my test environment to have a lot of desyncs beyond just the corporate card linking. So, I ended up figuring out what I did wrong when I tried to fix it last time, and fixing it for good this time.

**Comment by pkmnfrk** [comment]
Apparently it's still happening... bluh
